version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3001 -b 0.0.0.0 Puma
    ports:
      - "3001:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
