version: '2'
services:
  db:
    #environment:
    #  PGDATA: /data/postgres_db
    #volumes:
    #  - /data/postgres_data/docker_ohturubypg:/data/postgres_db
    volumes:
       - /data/postgres_db2
    image: postgres:9.6
    restart: unless-stopped
  web:
    build: .
    command: rails s -p 3001 -b 0.0.0.0 Puma
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      #RAILS_ENV: production
      RAILS_ENV: development
    restart: unless-stopped
