development:
  adapter: postgresql
  encoding: unicode
  database: ohturubypg
  pool: 5
  username: postgres
  password:
  host: db

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: ohturubypg
  pool: 5
  username: postgres
  password:
  host: db
